# -*- coding: utf-8 -*-
"""P1HW1_RoblesPerla.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m40qnlK0hjYP1IJOPrCO26bKdJllVVkk
"""

from os import supports_bytes_environ
 # Perla Robles
 # 02/10/2025
 # P1HW1
 # Using Python's input and print functions

print("-----Calculating Exponenets------")
print()
base_value = int(input("Enter an integer as the base value: "))
exponent_value = int(input("Enter an integer as the exponent: "))
value = base_value ** exponent_value
print()
print(base_value, "raised to the power of", exponent_value, "is",value, "!!")

print()
print("-----Additional and Substraction------")
print()
start_inter = int(input("Enter a starting integer: "))
add_inter = int(input("Enter an integer to add: "))
sub_inter= int(input("Enter an integer to subtract: "))
total= start_inter + add_inter - sub_inter
print()
print(start_inter, "+", add_inter, "-", sub_inter, "is equal to", total)

print()