# -*- coding: utf-8 -*-
"""P2HW1_RoblesPerla.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Is1ksYQfYjfYOyacHT8T-ipn6ksqYCyh
"""

# Perla Robles
# 02/25/2025
# P2HW1
# Ablilty to edit and enchace exiting programs

print("This program calculates and displays travel expenses ")
print()
budget = int(input("Enter Budget: "))
print()
destination = input("Enter you travel destination: ")
print()
gas = int(input("How much do you think you will spend on gas? "))
print()
hotel = int(input("Approximately, how much will you need for accomodation/hotel? "))
print()
food = int(input("Last, how much do you need for food? "))
print()
remaining_balance = budget - (gas + hotel + food)

print("-------------Travel Expenses------------")
print(f"{'Location:':<20}", destination)
print(f"{'Initial Budget:':<20}${budget:.2f}")
print(f"{'Fuel:':<20}${gas:.2f}")
print(f"{'Accomodation:':<20}${hotel:.2f}")
print(f"{'Food:':<20}${food:.2f}")
print()
print("--"*20)
print(f"{'Remaining Balance:':<20}${remaining_balance:.2f}")