# -*- coding: utf-8 -*-
"""P4HW1_RoblesPerla

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11wSUGK4TmlZ03x8KcC3rXpU5k9zXQUlS
"""

# Perla Robles
# 03/24/25
# P4HW1
# Program using a loop

# Creating an empty list to store grades
grade_list = []

num_score = int(input("How man scores do you want to enter? "))

print()

# Creating a loop through the number of scores entered by the user
for score in range(num_score):
  grade = int(input(f"Enter score # {score +1}: "))

  # Checking if the entered score is valid (between 0 and 100)
  while grade <0 or grade >100:

  # Printing an error message if the score is invalid
   print()
   print ("INVALID Score enter!!!")
   print ("Score should be between 0 and 100")

   # Asking the user to enter a valid score again
   grade = int(input(f"Enter score # {score +1} again: "))

  # Adding the valid score to the grade list
  grade_list.append(grade)
print()

print("--------Results--------")

print(f"Lowest Score: {min(grade_list)}")

grade_list.remove(min(grade_list))

# Printing the modified grade list (with the lowest score removed)
print(f"Modifies list: {grade_list}")

# Calculating the average score from the remaining grades
avg = sum(grade_list)/len(grade_list)

print(f"Scores Average: {avg:.2f}")

if avg >= 90:
   print('Grade : A')
elif avg >= 80:
    print('Grade : B')
elif avg >= 70:
    print('Grade : C')
elif avg >= 60:
    print('Grade : D')
else:
    print('Grade : F')

print("---"*10)